// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krlugvhjrreztmiwpghy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtybHVndmhqcnJlenRtaXdwZ2h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTcyOTMsImV4cCI6MjA2OTkzMzI5M30.ClZzahbfLtW8Qp9D3XepTGzNK0bB4f6ygW9y7OaR8g0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});